# Murgiltze klaseak <br><small>Zer izan behar dugu kontuan?</small>

Hizkuntza ofizial bi: Euskara eta gaztelania...

Hezkuntza sistemak Euskal Herrian elebitasuna oinarri:  
Helburua : Bi hizkuntzak ezagutzea

Nola sustatu bi hizkuntzen ikaste prozesua?  
Programa asko dago, hizkuntza biak hartzen dituzte kontuan.

Lau programa mota:

 + Segregazioa
 + Sumertsioa
 + Mantentzea
 + Murgilketa

## Segregazio programak

+ Ikasleen L1 erabiltzen da eta L2 ikasgaitzat
+ Ikasleek L2n maila noa lortzen dutenean L2n eskolatzeko aukera ikusten da
	* Azken hori ia ez da gertatzen eta emaitza akademiko pobreak
+ Ondorio negatiboak:
	* Ghettoak
	* Marginalizazioa
	
## Sumertsio programak

+ Hizkuntza eta kultura nagusian oinarritua
+ Asimilazioa du helburu (berezko kulturen galera)
+ Mendebaldeko herrialdeetan etorkinekin egiten da. 
	* Ijitoekin?
+ Ondorio negatiboak
	* Hezitzaileak ez dira prest egoten haurren behar linguistikoei aurre egiteko
	* L2n gaitasuna bermatzeko instrukzio bereziari denbora gutxi eskaintzen zaio.
	* Batera ikasten dira edukiak eta irakaskuntzarako hizkuntza
	* Ikasleen ebaluazioa hizkuntza eta kultura nagusiaren arabera



Moises-en kasua

https://www.youtube.com/watch?v=I6Y0HAjLKYI

+ Noiz eta nola iritsi zen Moises AEBra? Nola dakizu hori?
+ Ikasle ikuskeratik, zein dira bere ahulguneak eta bere indarguneak?
+ Moisesek bere irakaslearekin zein du oztopo nagusi?
+ Zein zailtasun ditu Moisesek eskolan eta eskolatik kanpo?
+ Zein zailtasun du irakasleak?
+ Zein rol du zuzendariak?
+ Nolako jarrera dute Moisesen lagunak eta familiak?
+ Zer egin liteke hori hobetzeko?
+ Eskola horretan ezer falta da? Zer?
+ Irakasle izan behar duzu-eta, zer diotsu bideoak?


## Mantentze programak

+ Ikasleek L2 ikasten dute beraien hizkuntza eta kultura galdu barik
+ Gutxiengoari zuzendua
+ Ikasleen L1 irakaskuntza tresna bezala erabiltzen da eta L2 apurka-apurka sartzen da.
+ Bi hizkuntzak izaten dira kontuan eskola amaitu arte

## Murgiltze programak

+ L2 programak hizkuntza eta kultura nagusiko ikasleei zuzendua
+ L2n oinarritutako irakaskuntza
+ Helburua: elebitasun eta *kulturabitasuna*
+ L1 mantentzen da: eskolan trataeragatik eta eskolaz kanpo egoeragatik
+ L2 naturalki ikastera bideratua

### Murgiltze modeloak

+ L2an hasteko unearen arabera
	* Murgiltze goiztiarra
	* Murgiltze atzeratua
	* Murgiltze berantiarra
+ L2an aritutako denbora
	* Murgiltze totala
	* Murgiltze partziala
+ Zenbat hizkuntza
	* Murgiltze sinplea
	* Murgiltze bikoitza https://www.youtube.com/watch?v=nUFO92j81ck
	
	
## Elebitasun motak

Elebitasun gehigarria: L1+ L2 (murgiltze programak)

Elebitasun kengarria: L1 galtzen da, eta L2ren identitate kulturala eta hizkuntza gailentzen da (sumertsio programak)

Euskal Herrian mota biak aurki ditzakegu


## Etorkinekin zein programa?

Gaur egun EHko eskolak eleanitzak eta kulturanitzak... zein programa da egokiena?

Ikasgela bereziak? L2ren garrantzia gela arruntera pasatzeko.

Ikasgela arrunta? Edukiak eta hizkuntzak batera

Euskal aukera bat: HIPI, Hizkuntza Indartzeko Programako Irakasleak

Gaztelania L1/Euskara L2 murgiltze programa

Etorkintzak - sumertsio programa

Nahiz eta instrukzioa beste hizkuntza batean izan, kasuak ez dira berberak.

Etorinek hainbat egoerari aurre egin behar diete:

[es Vs ko](https://www.youtube.com/watch?v=Z1PduFLoJ0Y)

## Hausnarketa ariketa

(15 min)

5 urteko umeak zarete eta gurasoekin beste herrialde batera bizitzera zoazte:

+ Nolakoa litzateke *shock kulturala*?
+ Zein zailtasun izango zenituzke eskolan? Kalean?
+ Kontuan izan erlijioa, hizkuntza, hezkuntza sistema, eguraldia ...

### Testuak

+ Irakurri
+ Sumertsioari buruzko galderak erantzun
+ Murgiltze eta sumertsioaren arteko ezberdintasunak aipatu

## Sumersioa vs. Murgiltzea

|Sumertsioa | Murgiltzea |
|:----------|-----------:|
|Derrigorrezkoa| Hautazkoa |
|Ikasle batzuk ezagutu eta beste batzuk ez | Gehienak ez du ezagutzen |
| Irakasle elebakarrak (ikasleen l1 ezagutu ez)| Irakasle elebidunak |
| Input-a ez dago egokituta | Input-a egokituta |
|Erroreak porrot legez interpretatu | L2 erroreak ikaste prozesuan ulertzen dira |
| Ikasleen L1 ez da egokia ezta estandarra ere | Ikasleen L1 gizartean ondo ikusia |
| L1 ez da erabilgarria eskolan | Eskolan L1 ere erabil daiteke |
| Ez da L1 irakasten | L1 ere irakasten da |

## Murgiltze klasearen arazo batzuk

+ Erabateko ulermena, baina mintzamen gaitasun mugatua garatzen da
+ Nahikotan murgiltze-klaseak jatorrizko hiztunaren mailatik urrun
+ L2 bat hitz egitea ez da hizkuntza batean hitzak bizkor esatea, baizik eta hizkuntzaren oinarrizko egituretan gaitasuna izatea (Hammerly, 1994) <BEGITTU!!!>
+ Frantsesezko murgiltze programetan *frenglish*; hemen *euskañola*
+ Hizkuntza-erroreen fosilizazioa goiz hasten da programotan (Lyster, 1998)
+ Input murriztua eta desegokia, hizkuntza erabiltzeko aukera urriak

**Hiztun minoritarioak**

+ Euskara L1 ikasleen kopuru baxua
+ Horrelako egoeran zaita euskaldunek murgiltzeko ikasleei euskara irakastea, baina erraza euskara castellanizatzea.
+ Euskara L1dun ikasleen hizkuntzari eutsi (gurasoekin berba egin etxean ere lan dezaten)

## Murgiltze klaseetan kontuan izatekoak

+ Input ulergarria (Krashen 1973)
	* Nahikoa kopuruan
	* Ulergarria
	* Interesgarria
	* Kalitatezkoa
+ Inputa Intake bihurtzen da
+ Nahikoa da?

## Murgiltze klasearen arazo batzuk

Kanadan Merrill Swain-ek (1985) ikusitakoak

+ Ulermen selektiboa: ikasleek mezua nolabait ulertzea lortzen dute, hizkuntzaren analisirik egin gabe. Hitzen bat, keinuak eta testuinguruaren laguntzaz mezua ulertzera iritsi eta horrekin nahikoa dute
+ Esanahiean ardaztutako metodologian, askotan, formak ez du axolarik: 
	Erroreak ez dira zuzentzen, bigarren mailako arazotzat hartzen da.
+ Inputa funtzionalki murriztua da geletan: eskolatik kanpoko hainbatt egoera, egitura lexikoa... ez da agertzen eta ez da sekula erabiltzen.
+ Edukian ardaztutako metodologian ekoizteko aukera gutxi egoten da; batez ere maila batetik gora. Edukia da nagusiena eta eskolaren eskema tradizionalak dira nagusiak.

## Kontuan hartu beharrekoak

+ Inputa ez da nahikoa L2 ikasteko. Outputa ere beharrezkoa da.
+ Ikasleak L2 erabili behar du eta ikaste prozesuko zailtasunak gainditu behar ditu.
+ Horretarako, outputak egokia eta zehatza izan behar du.
+ Bidea: komunikazio estrategiak landuaz lortzea.
+ Kaptazioaren hipotesia (Schmidt, 1990)
	* Igartzen ez dena ezin da ikasi.
+ Interakzioaren hipotesia (Long, 1983 eta 1996)
	* Ikasleen arteko komunikazioari garrantzia ematen dio
	
## Taldekako hausnarketako galderak

Zer egin dezake irakalseak umeen L2ren erabilera aktiboa eta esanguratsua sustatzeko murgiltze geletan?

Hitz egiten hitz eginez ikasten da. Baina murgiltze geletako haurrek ez dute eskolako hizkuntza ezagutzen eta irakaslearen zeregina izango da ume horiei L2n komunikatzeko behar dituzten hizkuntz baliabideak ematea. **Zer egin dezake irakasleak** ikaslea hizkuntza baliabidez hornitzeko?

## Proposamen batzuk klasean L2a sustatzeko

+ Giro egokia sortu
+ L2ren erabilera testuinguratua ahalbidetzen duten egoerak diseinatu
+ Hasieran, komunikazio egoera erritualizatuei eman garrantzia
+ Diseinatu umeentzako egoera komunikatibo erakargarriak
+ Proposatu umearen gogoko eginkizun eta gaiak
+ Espazioa eta denbora antolatu umeak berba egitea ahalbidetzeko
+ Ikasleen komunikazio premiak astzeko hizkuntza baliabide egokiak eta nahikoak eman
+ Umeak diskurtso-mota desberdinekin hartu-emanetan jarri
+ Umeen L1 errespetatu eta L2 erabiltzeko ahalegina afektiboki saritu

## Gelako erritualak

+ Ohiko egoerak, behin eta berriro errepikatzen direnak aldaketa gutxirekin (aurreikusten errazak, beraz)

Ahalbidetzen dute:

+ errutina interaktiboa sortzea
+ funtzio eta egitura komunikatibo eta linguistiko errazak eta laburrak erabiltzea, errepikakorrak
+ haurra seguruago sentitzea, berak parte hartzea erraztuz

## Gela hirueleduna

Frisiako gela bat: https://www.futurelearn.com/courses/multilingual-practices/0/steps/22654

+ Zein estrategia erabiltzen dituzte gelan hiru hizkuntza nagusiekin bestelako hizkuntzak integratzeko?
+ Antzekotasunik ikusten duzu euren eta gure eskolen artean?
+ Holako metodologia eskola guztietan eta hizkuntza guztiekin erabil dezakegu?
+ Zein aldaketa proposatzen dituzu(e)?