flowchart LR
    tab1["Kontestualizatutik"] --> tab2["Deskontestualizatura"]
    tab3["Elkarrizketatutik"] --> tab4["Bakarrizketatura"]
    tab5["Ahozko kolokialetik"] --> tab6["Idatzi prototipikora"]
