flowchart TD
    tab1["Kontestualizatutik"] --> tab2["Deskontestualizatura"]
    tab3["Elkarrizketatutik"] --> tab4["Bakarrizketatura"]
    tab5["ahozkotik"] --> tab6["idatzira"]

    classDef postit fill:#FFFACD,stroke:#333,stroke-width:2px,color:#000;
    class tab1,tab2,tab3,tab4,tab5,tab6 postit;